
#     _______     _______ ___         __    _____  ______ 
#    / ____\ \   / / ____|__ \       / /   |  __ \|  ____|
#   | (___  \ \_/ / (___    ) |_  __/ /_   | |__) | |__
#    \___ \  \   / \___ \  / /\ \/ / '_ \  |  _  /|  __|
#    ____) |  | |  ____) |/ /_ >  <| (_) | | | \ \| |____
#   |_____/   |_| |_____/|____/_/\_\\___/  |_|  \_\______|
#
# System 246/256 software revenge engineering
# MIT licensed.

IOP_BIN = acdev.irx
IOP_SRC_DIR = src/
IOP_INC_DIR = src/
IOP_OBJS = main.o imports.o exports.o

include $(PS2SDK)/Defs.make
include $(PS2SDK)/samples/Makefile.pref
include $(PS2SDK)/samples/Makefile.iopglobal